[location]
path = "synthetic/data"
overwrite = "true"

[data]
rec_filename = "recs.csv"
feature_filename = "items.csv"

[output]
filename = "synthetic_data_history_RuleBorda_weighted_product_allocation.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[allocation]
allocation_class = "weighted_product_allocation"

[choice]
choice_class = "whalrus_scoring"

[post]
postprocess_class = "exposure"

[context.properties]
compatibility_file = "compat.csv"

[allocation.properties]
compatibility_exponent = 2
fairness_exponent = 1

[choice.properties]
recommender_weight = 0.6
whalrus_rule = "RuleBorda"
tie_breaker = "Random"
ignore_weights = "false"

[post.properties]
full_filename = "Baseline_synthetic.csv"
summary_filename = "baseline_synthetic_RuleBorda_weighted_product_allocation.csv"
threshold = "none"
binary = "false"

[feature.one]
name = "0"
protected_feature = "0"
protected_values = [ 1,]

[feature.two]
name = "1"
protected_feature = "1"
protected_values = [ 1,]

[feature.three]
name = "2"
protected_feature = "2"
protected_values = [ 1,]

[agent.one]
name = "0"
metric_class = "mrr"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.three]
name = "2"
metric_class = "disparate_exposure"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.two]
name = "1"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.one.metric]
feature = "0"
target = 0.5

[agent.one.preference]
delta = 0.8
feature = "0"

[agent.three.metric]
feature = "2"
n_protected = 0.9
target = 2.0

[agent.three.preference]
delta = 0.7
feature = "2"

[agent.two.metric]
feature = "1"
proportion = 0.5

[agent.two.preference]
delta = 0.7
feature = "1"
