stages:
  run:
    cmd: python /Users/call/Github/scruf_d/__main__.py params.yaml
    deps:
      - params.yaml
    outs:
      - results/history.parquet
  postprocess:
    cmd: python post.py
    deps:
      - params.yaml
      - results/history.parquet
    metrics:
      - eval/metrics.json
  
#  save:
#    cmd: dvc push results/history.json
#    deps:
#      - results/history.json
#      - eval/metrics.json

#       outs:
#      - eval/metrics.json