stages:
  config_generation:
    cmd: python ../scruf_d/_toml_gen.py
    params:
    - config.rec_weight
    - config.choice
    - config.allocation
  run_scruf:
    cmd: python ../scruf_d/__main__MODIFY.py





