config:
  choice: ['RuleBorda', 'RuleCopeland']
  allocation: ['weighted_product_allocation']
  rec_weight: [0.1]
  folder_path: "../scruf-dvc-experiments/kiva/"
  base_toml: "../scruf-dvc-experiments/kiva/Rescore_weighted.toml"

