config:
  choice: ['RuleBorda', 'RuleCopeland', 'weighted_scoring']
  allocation: ['least_fair', 'product_lottery', 'weighted_product_allocation']
  rec_weight: [0.6]
  folder_path: "../scruf-dvc-experiments/synthetic/" #change here for new data
  base_toml: "../scruf-dvc-experiments/synthetic/synthetic_config.toml" #change here for new agent definitions/data

