[location]
path = "kiva/data"
overwrite = "true"

[data]
rec_filename = "recs_filter.csv"
feature_filename = "items.csv"

[output]
filename = "history_file_three_features_RuleCopeland_product_lottery_3.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[allocation]
allocation_class = "product_lottery"

[choice]
choice_class = "whalrus_scoring"

[post]
postprocess_class = "null"

[context.properties]
compatibility_file = "compat.csv"

[feature.one]
name = "COUNTRY_low_pfr"
protected_feature = "COUNTRY_low_pfr"
protected_values = [ 1,]

[feature.two]
name = "loan_buck_5"
protected_feature = "loan_buck_5"
protected_values = [ 1,]

[feature.three]
name = "ACTIVITY_low_pfr"
protected_feature = "ACTIVITY_low_pfr"
protected_values = [ 1,]

[agent.one]
name = "COUNTRY_low_pfr"
metric_class = "disparate_exposure"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.two]
name = "loan_buck_5"
metric_class = "mrr"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.three]
name = "ACTIVITY_low_pfr"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[allocation.properties]

[choice.properties]
recommender_weight = 0.1
whalrus_rule = "RuleCopeland"
tie_breaker = "Random"
ignore_weights = "false"

[agent.one.metric]
feature = "COUNTRY_low_pfr"
n_protected = 0.04
target = 5

[agent.one.preference]
delta = 0.9
feature = "COUNTRY_low_pfr"

[agent.two.metric]
feature = "loan_buck_5"
target = 0.5

[agent.two.preference]
delta = 0.8
feature = "loan_buck_5"

[agent.three.metric]
feature = "ACTIVITY_low_pfr"
proportion = 0.2

[agent.three.preference]
delta = 0.7
feature = "ACTIVITY_low_pfr"
