[location]
path = "kiva_1/data"
overwrite = "true"

[data]
rec_filename = "recs_1.csv"
feature_filename = "items.csv"

[output]
filename = "kiva.json"

[parameters]
list_size = 10
iterations = -1
initialize = "skip"
history_window_size = 100

[context]
context_class = "csv_context"

[context.properties]
compatibility_file = "compat.csv"

[feature]

[feature.one]
name = "COUNTRY_low_pfr"
protected_feature = "COUNTRY_low_pfr"
protected_values = [1]

[feature.two]
name = "loan_buck_5"
protected_feature = "loan_buck_5"
protected_values = [1]

[feature.three]
name = "ACTIVITY_low_pfr"
protected_feature = "ACTIVITY_low_pfr"
protected_values = [1]

[agent]

[agent.one]
name = "COUNTRY_low_pfr"
metric_class = "disparate_exposure"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.one.metric]
feature = "COUNTRY_low_pfr"
n_protected = 0.04
target = 4

[agent.one.preference]
delta = 0.9
feature = "COUNTRY_low_pfr"

[agent.two]
name = "loan_buck_5"
metric_class = "mrr"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.two.metric]
feature = "loan_buck_5"
target = 0.5

[agent.two.preference]
delta = 0.2
feature = "loan_buck_5"

[agent.three]
name = "ACTIVITY_low_pfr"
metric_class = "proportional_item"
compatibility_class = "context_compatibility"
preference_function_class = "cascade_preference"

[agent.three.metric]
feature = "ACTIVITY_low_pfr"
proportion = 0.3

[agent.three.preference]
delta = 0.7
feature = "ACTIVITY_low_pfr"


[allocation]
allocation_class = "weighted_product_allocation"

[allocation.properties]



[choice]
choice_class = "weighted_scoring"
[choice.properties]

recommender_weight = 0.1

[post]
postprocess_class = "exposure"

[post.properties]
full_filename = "kiva.csv"
summary_filename = "fairness.csv"
threshold = "none"
binary = "false"

